// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbBMVUEYLuJFkOFJIa14JnB-H-k1Mw92A',
    appId: '1:1090945564897:web:bb6f4e820c317b1a3cf7a0',
    messagingSenderId: '1090945564897',
    projectId: 'shoppe-535ea',
    authDomain: 'shoppe-535ea.firebaseapp.com',
    storageBucket: 'shoppe-535ea.appspot.com',
    measurementId: 'G-9ZF366K9CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYv83-NOKuhi_Gi1ms0Jr0W8-fKsUlWc',
    appId: '1:1090945564897:android:c6c9a88ebce810143cf7a0',
    messagingSenderId: '1090945564897',
    projectId: 'shoppe-535ea',
    storageBucket: 'shoppe-535ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLMoK297CeFmM_6BI8jtj8Z_r18-sW-0',
    appId: '1:1090945564897:ios:f980af886bf79ef83cf7a0',
    messagingSenderId: '1090945564897',
    projectId: 'shoppe-535ea',
    storageBucket: 'shoppe-535ea.appspot.com',
    androidClientId: '1090945564897-4pnnghq8cbudalulnfdflrjgi0jn4g6t.apps.googleusercontent.com',
    iosClientId: '1090945564897-adru08hfhos8dpvsh9e5g7ecg1i0qv3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.signup',
  );
}
